updated directory structure and compile against more python version

diff --git a/.github/workflows/ok-to-test-command.yml b/.github/workflows/ok-to-test-command.yml
--- a/.github/workflows/ok-to-test-command.yml
+++ b/.github/workflows/ok-to-test-command.yml
@@ -6,6 +6,10 @@ on:
 jobs:
   integration_test_cases:
     runs-on: self-hosted
+    strategy:
+      max-parallel: 1
+      matrix:
+        python-version: ['3.9']
     if: github.event_name == 'repository_dispatch'
     steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
@@ -13,31 +17,44 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
-      #- name: Set up Python 3.9.10
-      #  uses: actions/setup-python@v2
-      #  with:
-      #    python-version: '3.9.10'
-      - name: Install ansible
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
         run: |
-          virtualenv -p /usr/local/bin/python3.9 venv
-          source venv/bin/activate
-          pip install --upgrade pip
-          pip install ansible
-          pip install shyaml
+          pip install -r requirements.txt
       - name: Build and install the collection
         run: |
-          source venv/bin/activate
-          cd nutanix/ncp
           NAMESPACE=$(cat galaxy.yml | shyaml get-value namespace)
           COLLECTION_NAME=$(cat galaxy.yml | shyaml get-value name)
           VERSION=$(cat galaxy.yml | shyaml get-value version)
+          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
+          echo "COLLECTION_NAME=${COLLECTION_NAME}" >> $GITHUB_ENV
           ansible-galaxy collection build --force
           ansible-galaxy collection install ${NAMESPACE}-${COLLECTION_NAME}-${VERSION}.tar.gz --force
       - name: Run Integration test cases
         run: |
-          source venv/bin/activate
-          cd /home/${USER}/.ansible/collections/ansible_collections/nutanix/ncp
-          ansible-test integration --python 3.9 -v
+          cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
+          ansible-test integration --python ${{ matrix.python-version }} --coverage -v
+          ansible-test coverage report > coverage.txt
+
+      - name: Code Coverage Check
+        run:  |
+              cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
+              echo "Code coverage: Checking if code coverage is above threshold..."
+              export COVERAGE_THRESHOLD=70
+              echo "Threshold: $COVERAGE_THRESHOLD %"
+              totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
+              echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
+              echo "Current integration test coverage : $totalCoverage %"
+              if (( $(echo "$totalCoverage $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                  echo "Coverage passed"
+              else
+                  echo "Current integration test coverage is below threshold. Please add more integration tests or adjust threshold to a lower value."
+                  echo "Coverage check failed"
+                  exit 1
+              fi
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
@@ -49,6 +66,7 @@ jobs:
           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
           body: |
             >Integration test run status is : ${{ job.status }}
+            >Converage is : ${{ env.TOTAL_COVERAGE }} %
             >Job link https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
           reaction-type: hooray
 
@@ -74,9 +92,6 @@ jobs:
               ref
             });
             const check = checks.check_runs.filter(c => c.name === process.env.job);
-            console.log(check);
-            console.log(checks);
-            console.log(check.length)
             if (check.length == 0) {
               return "Check is not present, ignoring this step."
             }
@@ -86,4 +101,4 @@ jobs:
               status: 'completed',
               conclusion: process.env.conclusion
             });
-            return result; 
+            return result;
